### ISSUE TITLE
[11.0] ncf_manager: No deja crear una segunda compañía

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#101]
#### Impacted versions:
10.0

#### Steps to reproduce:
- Crear una segunda compañía (multi-company), e intentar ponerle nombre, el RNC o Cédula.

#### Current behavior:
```
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 5025, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 4920, in _onchange_eval
    method_res = method(self)
  File "/odoo/odoo-server/src/custom/iterativo/dominican_addons/ncf_manager/models/res.py", line 57, in onchange_company_vat
    self.partner_id.validate_rnc_cedula(self.vat)
  File "/odoo/odoo-server/src/custom/iterativo/dominican_addons/ncf_manager/models/res.py", line 139, in validate_rnc_cedula
    "name", False) or dgii_vals.get("commercial_name", "")
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 955, in __set__
    record.ensure_one()
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 4296, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.partner()
```
#### Expected behavior:
La compañía debería tomar el nombre desde la DGII.

**Comment by yasmanycastillo** [comment]
@gustavovalverde por favor dale un review a este issue.
