### ISSUE TITLE
validacion facturas compras

### ISSUE THREAD

**Issue by NB5055** [odoo-dominicana/l10n-dominicana#212]
#### Impacted versions:

10.0, 11.0

#### Steps to reproduce:

Crear una Factura de Proveedor e intentar validarla

#### Current behavior:

Cuando se intenta validar una factura de proveedor con las nuevas secuencias en un diario configurado para validar NCF con la DGII esta fallando esto debido a que los **WS** de la DGII a los que se conecta el **STDNUM** no estan funcionando como deberian.

#### Expected behavior:

validar NCF facturas de proveedor

**Comment by gustavovalverde** [comment]
Sí, mientras tanto debes quitar el cotejo de validación con el WebService; actualmente ninguno de los Webservices de la DGII están entregando esta información.

**Comment by ctactuk** [comment]
Saludos.  donde está este cotejo?

**Comment by gustavovalverde** [comment]
En el diario.

**Comment by ctactuk** [comment]
Con el cotejo y sin el cotejo da me está dando este error :(

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 5087, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4982, in _onchange_eval
    method_res = method(self)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\ncf_manager\models\res.py", line 172, in onchange_partner_name
    result = self.validate_rnc_cedula(self.name)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\ncf_manager\models\res.py", line 153, in validate_rnc_cedula
    dgii_vals = rnc.check_dgii(number)
AttributeError: module 'stdnum.do.rnc' has no attribute 'check_dgii'

**Comment by gustavovalverde** [comment]
Cierro este error, porque ya la validación se está realizando de forma exitosa contra la DGII.

**Comment by jjdelarosa** [comment]
@gustavovalverde se puede colocar un mensaje o alerta cuando la validación o conexión no pudo ser existosa, y quede en status "Pendiente por Validar", esto es en caso si se cae el servidor de la DGII. 

> File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.dgii.gov.do', port=80): Max retries exceeded with url: /app/WebApps/ConsultasWeb/consultas/ncf.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35f1f75630>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido',))
