### ISSUE TITLE
[11.0] Error al colocar tasa factura de compra

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#222]
En las facturas de compras, si el usuario trata de colocar la tasa del día manual o de otro banco Odoo presenta el siguiente error:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3466, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "update_rate_wizard_id_seq" does not exist
LINE 1: ...uid", "create_date", "write_date") VALUES(nextval('update_ra...
```

**Comment by yasmanycastillo** [comment]
Saludos, @edsersolis como puedo reproducir este error? Pues hago el cambio de moneda mas no veo la opcion de cambiarla como se mostraba en la 10, prove con el branch develop y 11.0.

**Comment by edsersolis** [comment]
@yasmanycastillo Crea una factura de compra en USD, haz click sobre la tasa y allí trata de cambiarla manual o tomandola de otro banco.

**Comment by yasmanycastillo** [comment]
@edsersolis he tratado pero no veo el boton para actualizar la tasa, ni en el branch develop ni en el 11.0
