### ISSUE TITLE
[ncf_purchase] Error al instalar

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#264]
Está presentandose este error al tratar de instalar en una DB existente.

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fa371aafdd8>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fa371aafdd8>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/src/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo/odoo-server/src/odoo/odoo/modules/registry.py", line 307, in init_models
    model.init()
  File "/odoo/odoo-server/src/custom/iterativo/dominicana-premium/invoice_payment_method/models/account_invoice.py", line 41, in init
    self.search([]).compute_payment_method()
  File "/odoo/odoo-server/src/custom/iterativo/dominicana-premium/invoice_payment_method/models/account_invoice.py", line 13, in compute_payment_method
    rec.payment_method = False
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 980, in __set__
    record.write({self.name: write_value})
  File "/odoo/odoo-server/src/odoo/addons/purchase/models/account_invoice.py", line 227, in write
    result = result and super(AccountInvoice, invoice).write(vals)
  File "/odoo/odoo-server/src/odoo/addons/mail/models/mail_thread.py", line 270, in write
    track_self = self.with_context(lang=self.env.user.lang)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1001, in _compute_value
    self.compute(records)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 589, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 4754, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1042, in determine_value
    record._prefetch_field(self)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 2646, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 2590, in read
    self._read_from_database(stored, inherited)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 2709, in _read_from_database
    cr.execute(query_str, params)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column res_partner.purchase_journal_id does not exist
LINE 1: ...e","res_partner"."expense_type" as "expense_type","res_partn...
                                                             ^
```

**Comment by mamcode** [comment]
@edsersolis Intento reproducir el error y nada. He instalado en una nueva bd sin data demo, instalo primero ncf_manager y luego ncf_purcase y todo OK. Lo que me parece es que estaba instalado en esta BD una versión de ncf_manager que incluía el campo purcase_journal_id, es decir la versión del 
PR #238 antes de separar la funcionalidad de diario de compras por defecto a ncf_purchase. Deberia 
servir lo siguiente: 

- Asegurarse de estar corriendo el ultimo commit de la rama 11.0.
- Reiniciar el servicio.
- Actualizar el modulo ncf_manager.
- Instalar modulo ncf_purchase.

**Comment by Raudy2** [comment]
https://gist.github.com/Raudy2/3d7273ace3d28076ccffa8984b6b2556 tengo el mismo problema Y ya probe todos los pasos anteriores
