### ISSUE TITLE
Al crear un cliente se produce este error

### ISSUE THREAD

**Issue by elfred05** [odoo-dominicana/l10n-dominicana#289]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 5099, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4994, in _onchange_eval
    method_res = method(self)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\ncf_manager\models\res.py", line 175, in onchange_partner_name
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\ncf_manager\models\res.py", line 156, in validate_rnc_cedula
    def rewrite_due_date(self):
AttributeError: module 'stdnum.do.rnc' has no attribute 'check_dgii'

**Comment by akevinieron** [comment]
Ese error ocurre porque necesitas actualizar la libreria de Python llamada stdnum al menos a la version 1.8, recomendable que instales la ultima que hasta ahora es la 1.9

**Comment by JorgeDDW** [comment]
Para resolver el error stdnum.check_dgii

1. `apt-get install python3-pip`
2. `pip3 install python-stdnum==1.9`

**Comment by anyeloroy** [comment]
Hola,

Como indico @JorgeDDW , es la forma de actualizar el [stdnum](https://pypi.org/project/python-stdnum/).

**Comment by angeljgonzalezr** [comment]
> Para resolver el error stdnum.check_dgii
> 
> 1. `apt-get install python3-pip`
> 2. `pip3 install python-stdnum==1.9`

Es posible instalar esta libreria en Windows?

**Comment by JorgeDDW** [comment]
> > Para resolver el error stdnum.check_dgii
> > 
> > 1. `apt-get install python3-pip`
> > 2. `pip3 install python-stdnum==1.9`
> 
> Es posible instalar esta libreria en Windows?

Por supuesto, solo debes de tener las variables de Python bien configuradas.
De lo contrario vas a tener problemas para que te funcione.
Si estas en windows, descarta el paso 1 y el instalador de Python 3 te debio de instalar el gestor de paquetes `pip` asi que vete directo al paso 2.

**Comment by angeljgonzalezr** [comment]
> > > Para resolver el error stdnum.check_dgii
> > > 
> > > 1. `apt-get install python3-pip`
> > > 2. `pip3 install python-stdnum==1.9`
> > 
> > 
> > Es posible instalar esta libreria en Windows?
> 
> Por supuesto, solo debes de tener las variables de Python bien configuradas.
> De lo contrario vas a tener problemas para que te funcione.
> Si estas en windows, descarta el paso 1 y el instalador de Python 3 te debio de instalar el gestor de paquetes `pip` asi que vete directo al paso 2.

Gracias, logre instalarlo. Probare en ubuntu, ya que a pesar de instalarse el mensaje persiste y en ocasiones presenta el blank page after login.
