### ISSUE TITLE
Error Creating new costumer/company with RNC/CEDULA

### ISSUE THREAD

**Issue by reneivanxd** [odoo-dominicana/l10n-dominicana#307]
#### Impacted versions
11
#### Steps to reproduce
Try to create a new company or customer with RNC or Cedula
#### Current behavior
Error is presented
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 80, in send
    fp = self.u2open(u2request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 127, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 675, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib/python3.5/urllib/request.py", line 613, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 307: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/suds/client.py", line 747, in send
    reply = self.options.transport.send(request)
  File "/usr/lib/python3/dist-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 90, in send
    raise TransportError(e.msg, e.code, e.fp)
suds.transport.TransportError: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4995, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4891, in _onchange_eval
    method_res = method(self)
  File "/home/pibukor/odoo/addons/ncf_manager/models/res.py", line 175, in onchange_partner_name
    result = self.validate_rnc_cedula(self.name)
  File "/home/pibukor/odoo/addons/ncf_manager/models/res.py", line 156, in validate_rnc_cedula
    dgii_vals = rnc.check_dgii(number)
  File "/usr/local/lib/python3.5/dist-packages/stdnum/do/rnc.py", line 146, in check_dgii
    IMEI='')
  File "/usr/lib/python3/dist-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 705, in invoke
    result = self.send(soapenv)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 752, in send
    return self.process_reply(content, e.httpcode, tostr(e))
  File "/usr/lib/python3/dist-packages/suds/client.py", line 819, in process_reply
    raise Exception((status, description))
Exception: (307, 'Temporary Redirect')
#### Expected behavior
the costumer/company  name should be loaded

**Comment by gustavovalverde** [comment]
This problem is caused by stdnum (an external library); I already made a PR to it https://github.com/arthurdejong/python-stdnum/commit/e31ff954d46190e06a4473c7213ad386c3a75e24

To update the library you need to:
pip install --upgrade git+https://github.com/arthurdejong/python-stdnum.git
