### ISSUE TITLE
Error al crear factura KeyError: 'purchase_id'

### ISSUE THREAD

**Issue by octagonosrl** [odoo-dominicana/l10n-dominicana#311]
#### Impacted versions
12.0
#### Steps to reproduce
Entrar a facturas de clientes > Crear Factura
#### Current behavior
El comportamiento actual es que lanza un error de key error KeyError: 'purchase_id'
#### Expected behavior
El comportamiento esperado es que entre a la vista formulario de las facturas y se puedan registrar los campos.

**Comment by akevinieron** [comment]
Por favor, puede enviar screenshot o copy/paste del error

**Comment by octagonosrl** [comment]
`Odoo Server Error
Traceback (most recent call last):
  File "/odoo/12odoo/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/12odoo/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/12odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/12odoo/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/12odoo/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/12odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/12odoo/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/12odoo/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/12odoo/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/12odoo/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/12odoo/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/12odoo/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/12odoo/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/12odoo/odoo/odoo/models.py", line 5429, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/odoo/12odoo/odoo/odoo/models.py", line 5282, in _onchange_eval
    method_res = method(self)
  File "/home/edev/PycharmProjects/l10n-dominicana-12/ncf_manager/models/account_invoice.py", line 306, in _onchange_origin
    purchase_ids = self.invoice_line_ids.mapped('purchase_id')
  File "/odoo/12odoo/odoo/odoo/models.py", line 4798, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/odoo/12odoo/odoo/odoo/models.py", line 4782, in _mapped_func
    vals = func(self)
  File "/odoo/12odoo/odoo/odoo/models.py", line 5048, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: 'purchase_id'`

**Comment by alex071995** [comment]
Ese onchange esta mapeando un campo en las lineas de la factura que no existe.

Dos cosas pasan aqui:

  1. Se equivocaron en la consulta a este campo (ya que en el core de odoo no existe).
  2. Agregaron ese campo en un modulo extra y no lo agregaron a la dependencia ni al repositorio.

Soluciones:

  1. Elimnar dicha funcion.
  2. Agregar la depencia del modulo extra.

**Comment by fow903** [comment]
A mi también me pasa, hice lo mismo que @octagonosrl  con el try catch en lo que se resuelve el issue.

**Comment by gustavovalverde** [comment]
Cerrado con este commit: d33a686ba6fd9b69dec1b29e82c63022bf127e52

**Comment by gustavovalverde** [comment]
Pueden hacer update y validar.

**Comment by esantos-octagono** [comment]
Gracias @gustavovalverde
