### ISSUE TITLE
Error al hacer click en el menu Contactos

### ISSUE THREAD

**Issue by ctactuk** [odoo-dominicana/l10n-dominicana#321]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/models.py", line 1295, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/odoo11/odoo/models.py", line 1295, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/odoo11/addons/mail/models/mail_thread.py", line 372, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/odoo11/odoo/models.py", line 1374, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/odoo11/odoo/addons/base/res/res_partner.py", line 317, in _fields_view_get
    res = super(Partner, self)._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/odoo11/odoo/models.py", line 1337, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 727, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 676, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 654, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 516, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<xpath expr="//field[@name='property_supplier_payment_term_id']">' no puede ser localizado en la vista padre

Contexto del error:
Vista `ncf.purchase.partner.form`
[view_id: 1511, xml_id: ncf_purchase.view_partner_form, model: res.partner, parent_id: 112]

**Comment by jlopezg** [comment]
Hola @ctactuk 

Podrías proporcionar los siguientes datos:

**Impacted versions**

**Steps to reproduce**

**Current behavior**

**Expected behavior**

**Video/Screenshot link (optional)**

**Comment by yasmanycastillo** [comment]
Saludos @ctactuk podrias verificar que el usuario con que intentas ver el contacto tiene permisos de Facturacion. Esto es debido a que el campo de diarios esta en la pestaña de Contabilidad en la ficha del cliente. Una opcion para evitar este error seria moverlo a Ventas y Compras, @gustavovalverde que opinas?

**Comment by gustavovalverde** [comment]
Posiblemente sea lo mejor @yasmanycastillo

**Comment by gustavovalverde** [comment]
Closed by 8ccc3c77d1406ad29175f1cbdffd4fd3c3cd0a56
