### ISSUE TITLE
crear cliente

### ISSUE THREAD

**Issue by armandorg81** [odoo-dominicana/l10n-dominicana#369]
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 642, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 684, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 334, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 101, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 327, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 942, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 507, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 895, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 887, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 689, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 680, in call_kw_multi
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 5537, in onchange
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 5435, in _onchange_eval
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\ncf_manager\models\res.py", line 186, in onchange_partner_name
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\ncf_manager\models\res.py", line 167, in validate_rnc_cedula
NameError: global name 'rnc' is not definedOdoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 642, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 684, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 334, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 101, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 327, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 942, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 507, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 895, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 887, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 689, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 680, in call_kw_multi
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 5537, in onchange
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 5435, in _onchange_eval
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\ncf_manager\models\res.py", line 186, in onchange_partner_name
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\ncf_manager\models\res.py", line 167, in validate_rnc_cedula
NameError: global name 'rnc' is not defined

**Comment by gustavovalverde** [comment]
Debes instalar el python-stdnum
