### ISSUE TITLE
Error al consultar cédula cliente en Dgii

### ISSUE THREAD

**Issue by ctactuk** [odoo-dominicana/l10n-dominicana#397]
#### Impacted versions
Odoo 11

#### Steps to reproduce
Facturar -> Ventas -> CLientes -> (click en el cliente) -> (escribir la cedula del cliente)

#### Video/Screenshot link (optional)
![error_dgii](https://user-images.githubusercontent.com/4774542/57935825-b0e60880-7890-11e9-8804-54ddba80cc7a.gif)

#### Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/suds/transport/http.py", line 82, in send
    fp = self.u2open(u2request)
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/suds/transport/http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 735, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib/python3.6/urllib/request.py", line 673, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 307: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/suds/client.py", line 613, in send
    reply = self.options.transport.send(request)
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/suds/transport/http.py", line 94, in send
    raise TransportError(e.msg, e.code, e.fp)
suds.transport.TransportError: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/models.py", line 5099, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/odoo11/odoo/models.py", line 4994, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/odoo11/addons/ncf_manager/models/res.py", line 201, in onchange_partner_vat
    result = self.validate_rnc_cedula(self.vat)
  File "/opt/odoo/odoo11/addons/ncf_manager/models/res.py", line 170, in validate_rnc_cedula
    dgii_vals = rnc.check_dgii(number)
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/stdnum/do/rnc.py", line 146, in check_dgii
    IMEI='')
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/suds/client.py", line 677, in process_reply
    raise Exception((status, description))
Exception: (307, 'Temporary Redirect')

**Comment by dixgrake** [comment]
@ctactuk pip3 install python-stdnum, error por la librerías que debes de instarla.

**Comment by ctactuk** [comment]
saludos,

corrí pip3 list en la terminal y me arroja que lo tengo instalado como se ve en la imagen:

![image](https://user-images.githubusercontent.com/4774542/58038416-e8a5b800-7afd-11e9-8c50-7b04d8dab254.png)

**Comment by ctactuk** [comment]
Resuelto, estaba tomando una versión que no era de python.
