### ISSUE TITLE
[11.0] ncf_manager: Error al abrir diario en contabilidad

### ISSUE THREAD

**Issue by JPayrol** [odoo-dominicana/l10n-dominicana#398]
#### Impacted versions
 Odoo 11

#### Steps to reproduce
Facturar -> Contabilidad -> Diario -> (click en Diario) -> (Click en cualquier Diario)
#### Current behavior
Buen día, este error ocurre cuando instalo el NCF Manager, y trato de entrar a la opción diario en contabilidad, me imagino que tenga que ver con el chequeo del RNC, opción que active, pero que ahora no la necesito.

Saludos

Error:

Odoo Server Error

Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__

value = record.env.cache.get(record, self)

File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get

value = self._data[field][record.id][key]

KeyError: <odoo.api.Environment object at 0x7f8deabcaac8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception

return super(JsonRequest, self)._handle_exception(exception)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception

raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])

File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise

raise value

File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch

result = self._call_function(**self.params)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function

return checked_call(self.db, *args, **kwargs)

File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper

return f(dbname, *args, **kwargs)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call

result = self.endpoint(*a, **kw)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__

return self.method(*args, **kw)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap

response = f(*args, **kw)

File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 931, in call_kw

return self._call_kw(model, method, args, kwargs)

File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw

return call_kw(request.env[model], method, args, kwargs)

File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw

return call_kw_multi(method, model, args, kwargs)

File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi

result = method(recs, *args, **kwargs)

File "/usr/lib/python3/dist-packages/odoo/models.py", line 2601, in read

values[name] = field.convert_to_read(record[name], record, use_name_get)

File "/usr/lib/python3/dist-packages/odoo/models.py", line 4754, in __getitem__

return self._fields[key].__get__(self, type(self))

File "/usr/lib/python3/dist-packages/odoo/fields.py", line 941, in __get__

self.determine_value(record)

File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in determine_value

self.compute_value(recs)

File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1008, in compute_value

self._compute_value(records)

File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1001, in _compute_value

self.compute(records)

File "/usr/lib/python3/dist-packages/odoo/addons_externos/l10n-dominicana-11.0/ncf_manager/models/account.py", line 28, in check_ncf_ready

self.ensure_one()

File "/usr/lib/python3/dist-packages/odoo/models.py", line 4362, in ensure_one

raise ValueError("Expected singleton: %s" % self)

ValueError: Expected singleton: account.journal(1, 4, 5)

#### Expected behavior
Mostrar el Diario

#### Video/Screenshot link (optional)

![Odoo NCF Error](https://user-images.githubusercontent.com/50749075/58263837-c785d700-7d4a-11e9-946b-475f96388d77.png)

**Comment by ctactuk** [comment]
Lo mismo me pasa.!

**Comment by akevinieron** [comment]
No he podido reproducir este error. Podrias por favor hacer update de este modulo y volver a probarlo?

**Comment by JPayrol** [comment]
Ya pueden cerrar este reporte, desaparecio el error cuando actualize a otra version de la imagen virtual que estoy utilizando.
Gracias
