### ISSUE TITLE
Error al tratar de imprimir factura de proveedor y de cliente.

### ISSUE THREAD

**Issue by ctactuk** [odoo-dominicana/l10n-dominicana#399]
#### Impacted versions
11.0
#### Steps to reproduce
Facturar->Compras->Facturas de proveedor-> (selecciona factura) -> imprimir.

Al tratar de imprimir factura de proveedor y de cliente.
#### Video/Screenshot link (optional)
![error_factura_proveedor_cliente](https://user-images.githubusercontent.com/4774542/58109241-46e4a080-7bbb-11e9-839c-bae9b80b9aa3.gif)

#### Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/odoo11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7fb0c9c35ae8>, 'ncf_invoice_template.dgii_external_layout', ('es_DO', True, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/odoo11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View.get_view_id at 0x7fb0a88d3510>, 1, 'ncf_invoice_template.dgii_external_layout', (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/odoo11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fb0c2b2af28>, 'ncf_invoice_template.dgii_external_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 369, in get_template
    document = options.get('load', self.load)(template, options)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 1103, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-239>", line 2, in get_view_id
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo11/addons/website/models/ir_ui_view.py", line 92, in get_view_id
    return super(View, self).get_view_id(xml_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 1115, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1344, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1335, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1324, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: ncf_invoice_template.dgii_external_layout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 1620, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 1569, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_actions_report.py", line 628, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_actions_report.py", line 666, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_actions_report.py", line 470, in render_template
    return view_obj.render_template(template, values)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 1208, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/odoo11/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/opt/odoo/odoo11/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 1217, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in _compiled_fn
    raise e
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_486_921
  File "<template>", line 2, in body_call_content_920
  File "<template>", line 3, in foreach_919
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in _compiled_fn
    raise e
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_document_with_payments_997
  File "<decorator-gen-44>", line 2, in compile
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 77, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 289, in compile
    element, document = self.get_template(template, options)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 373, in get_template
    raise QWebException("load could not load template", name=template)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: None
Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/odoo11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7fb0c9c35ae8>, 'ncf_invoice_template.dgii_external_layout', ('es_DO', True, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/odoo11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View.get_view_id at 0x7fb0a88d3510>, 1, 'ncf_invoice_template.dgii_external_layout', (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/odoo11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fb0c2b2af28>, 'ncf_invoice_template.dgii_external_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 369, in get_template
    document = options.get('load', self.load)(template, options)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 1103, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-239>", line 2, in get_view_id
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo11/addons/website/models/ir_ui_view.py", line 92, in get_view_id
    return super(View, self).get_view_id(xml_id)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_ui_view.py", line 1115, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1344, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1335, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo11/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1324, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: ncf_invoice_template.dgii_external_layout

load could not load template
Template: ncf_invoice_template.dgii_external_layout

**Comment by ctactuk** [comment]
Al parecer ya a este modulo no le dan seguimiento a los issues.!! :(

**Comment by akevinieron** [comment]
En realidad sí se le da seguimiento, pero son pocos los que aportan su tiempo para mejorar esto.

Según veo en el screen capture que enviaste estas tratando de imprimir una factura a proveedor que esta cancelada, eso es muy poco común. 

De todos modos he probado hacer eso que comentas en este isuue y no he logrado reproducir el error. Podrias probarlo en una base de datos nueva?

**Comment by ctactuk** [comment]
La verdad es la ultima version del modulo para odoo 11 que tiene issues en general, como por ejemplo el caso de que me da error al intentar abrir la ventada de editar un dialo, Solo fue para grabar el gif que utilice esta factura cancelada, lo que a mi enterder no debiera dar ningun problema para imprimirla aunque este cancelada.

**Comment by akevinieron** [comment]
Yo utilizo ambas funciones a diario en v11 y no he experimentado dichos problemas. Tambien lo acabo de probar en una nueva instalacion. Podrias probarlo en una nueva instalacion y dejarme saber que tal?

**Comment by ctactuk** [comment]
@akevinieron Disculpa manana estare haciendo otra prueba, te dejo saber si todo va bien con este issue.

**Comment by ctactuk** [comment]
Saludos, Esta parte ya la resolvi, solo me falta este issue #398  de los diarios que no he podido resolver.!

**Comment by ctactuk** [comment]
Resuelto el problema
