### ISSUE TITLE
Error al cencelar Factura

### ISSUE THREAD

**Issue by ctactuk** [odoo-dominicana/l10n-dominicana#401]
#### Impacted versions
[ V 11 ]
#### Steps to reproduce
Facturar->Facturas de Cliente -> ( clic en factura ) -> cancelar factura

#### Video/Screenshot link (optional)
![cancelarFactura](https://user-images.githubusercontent.com/4774542/58906023-0d428800-86d9-11e9-926b-7b854f5e5090.gif)

#### Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3394, in create
    record = self.browse(self._create(old_vals))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3487, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "account_invoice_cancel_id_seq" does not exist
LINE 1: ...uid", "create_date", "write_date") VALUES(nextval('account_i...
                                                             ^

**Comment by akevinieron** [comment]
@ctactuk Hey, este error no es posible reproducirlo en un ambiente 'estable'. Recomendación: Si estas en producción valora la posibilidad de instalar Odoo sobre linux con el source code y dejar Windows de lado.

Hay algunos temas de performance cuando Odoo trabaja sobre windows y si no tienes instalado con el source code es un poco mas dificil actualizar la version de tu codigo.

**Comment by akevinieron** [comment]
Por cierto, este issue sera cerrado por no ser un problema actual de la localización.
