### ISSUE TITLE
Error en generacion factura de cliente de tipo compañia antes creado

### ISSUE THREAD

**Issue by CodeVerify** [odoo-dominicana/l10n-dominicana#417]
saludos,

Probando el modulo me di cuenta de que los clientes tipo compañia al generar una segunda factura de x producto genera un error de tipo que no puede validar el rnc: 
(Odoo comunnity version 11)

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 134, in create_invoices
    sale_orders.action_invoice_create(final=True)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/sale.py", line 427, in action_invoice_create
    invoice = inv_obj.create(inv_data)
  File "/mnt/extra-addons/ncf_manager/models/account_invoice.py", line 452, in create
    ] or not rnc.check_dgii(str(partner_id.vat)):
NameError: name 'rnc' is not defined

***File "/mnt/extra-addons/ncf_manager/models/account_invoice.py", line 452, in create
] or not rnc.check_dgii(str(partner_id.vat)):
NameError: name 'rnc' is not defined***

**Comment by CodeVerify** [comment]
Resuelto!!

Comando:
**### pip3 install python-stdnum --upgrade**

simplejson
zeep>=3.2.0
python-stdnum>=1.11

python-stdnum
