### ISSUE TITLE
Crédito fiscal

### ISSUE THREAD

**Issue by odooscio** [odoo-dominicana/l10n-dominicana#453]
Cuando intento crear una factura para crédito fiscal me sale el siguiente error, con las demás posiciones fiscales no.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/suds/transport/http.py", line 82, in send
    fp = self.u2open(u2request)
  File "/usr/local/lib/python3.6/dist-packages/suds/transport/http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 735, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib/python3.6/urllib/request.py", line 673, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 307: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 613, in send
    reply = self.options.transport.send(request)
  File "/usr/local/lib/python3.6/dist-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/usr/local/lib/python3.6/dist-packages/suds/transport/http.py", line 94, in send
    raise TransportError(e.msg, e.code, e.fp)
suds.transport.TransportError: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/sale/wizard/sale_make_invoice_advance.py", line 135, in create_invoices
    sale_orders.action_invoice_create()
  File "/odoo/odoo-server/addons/sale/models/sale.py", line 582, in action_invoice_create
    invoice = inv_obj.create(inv_data)
  File "<decorator-gen-249>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/odoo/odoo-server/addons/extras/ncf_manager/models/account_invoice.py", line 452, in create
    ] or not rnc.check_dgii(str(partner_id.vat)):
  File "/usr/local/lib/python3.6/dist-packages/stdnum/do/rnc.py", line 146, in check_dgii
    IMEI='')
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 677, in process_reply
    raise Exception((status, description))
Exception: (307, 'Temporary Redirect')

**Comment by gustavovalverde** [comment]
Este error normalmente es por falta de una actualización en los requirements.txt

Revisa que tengas la misma versión en tu environment de python que el indicado.
