### ISSUE TITLE
Ayuda con la instalación 

### ISSUE THREAD

**Issue by MarioGuzmanP** [odoo-dominicana/l10n-dominicana#463]
Saludos

Soy nuevo en Odoo y por ende aquí también,
Instale Odoo en Win10 y me funciona bien pero el ncf manager no busca con el rnc en la dgii.

Leí qué hay que instalar los requerimientos, pero honestamente no se cómo hacerlo.

Podría alguien ser tan amable de guiarme un poco?

**Comment by diegoalmonte** [comment]
Hola

He intentado instalar los Requirements en multiples ocasiones tanto en mi computador con Win 7 y en un servidor de Ubuntu, pero NO logro poner a funcionar esta herramienta, ya casi me estoy dando por vencido :(

Aqui copio el error que me da por si alguien puede ayudarme

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/suds/transport/http.py", line 82, in send
    fp = self.u2open(u2request)
  File "/usr/local/lib/python3.7/dist-packages/suds/transport/http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 734, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib/python3.7/urllib/request.py", line 672, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 307: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/suds/client.py", line 613, in send
    reply = self.options.transport.send(request)
  File "/usr/local/lib/python3.7/dist-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/usr/local/lib/python3.7/dist-packages/suds/transport/http.py", line 94, in send
    raise TransportError(e.msg, e.code, e.fp)
suds.transport.TransportError: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoosrc/12.0/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoosrc/12.0/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoosrc/12.0/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoosrc/12.0/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoosrc/12.0/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoosrc/12.0/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoosrc/12.0/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoosrc/12.0/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoosrc/12.0/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoosrc/12.0/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoosrc/12.0/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoosrc/12.0/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoosrc/12.0/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoosrc/12.0/odoo/odoo/models.py", line 5510, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoosrc/12.0/odoo/odoo/models.py", line 5354, in _onchange_eval
    method_res = method(self)
  File "/opt/odoosrc/extra-addons/ncf_manager/models/res.py", line 197, in onchange_partner_name
    result = self.validate_rnc_cedula(self.name)
  File "/opt/odoosrc/extra-addons/ncf_manager/models/res.py", line 176, in validate_rnc_cedula
    dgii_vals = rnc.check_dgii(number)
  File "/usr/local/lib/python3.7/dist-packages/stdnum/do/rnc.py", line 146, in check_dgii
    IMEI='')
  File "/usr/local/lib/python3.7/dist-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python3.7/dist-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/usr/local/lib/python3.7/dist-packages/suds/client.py", line 677, in process_reply
    raise Exception((status, description))
Exception: (307, 'Temporary Redirect')

**Comment by MikeHiciano** [comment]
saludos @diegoalmonte 

creo que este issue te puede aclarar tus dudas:

https://github.com/odoo-dominicana/l10n-dominicana/issues/390#issuecomment-490744709

**Comment by MarioGuzmanP** [comment]
> Saludos
> 
> para hacerlo solo tienes que utilizar el comando
> 
> `pip install -r [ruta del requierents.txt]`

Podrías explicarme con más detalles???    

Soy nuevo y estoy aprendiendo ahora

Gracias de antemano

**Comment by gustavovalverde** [comment]
Hola Mario, preguntas de asistencias por favor realizarlas por esta vía: https://t.me/odoord
