### ISSUE TITLE
Error al generar informes DGII

### ISSUE THREAD

**Issue by ljacobo** [odoo-dominicana/l10n-dominicana#477]
Al querer generar los reportes de la DGII, da el siguiente error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/dgii_reports/models/dgii_report.py", line 830, in generate_report
    self._generate_report()
  File "/mnt/extra-addons/dgii_reports/models/dgii_report.py", line 818, in _generate_report
    self._compute_607_data()
  File "/mnt/extra-addons/dgii_reports/models/dgii_report.py", line 618, in _compute_607_data
    payments = self._get_sale_payments_forms(inv)
  File "/mnt/extra-addons/dgii_reports/models/dgii_report.py", line 446, in _get_sale_payments_forms
    for payment in Invoice._get_invoice_payment_widget(invoice_id):
TypeError: _get_invoice_payment_widget() takes 1 positional argument but 2 were given

**Comment by gilbertocomas** [comment]
> Al querer generar los reportes de la DGII, da el siguiente error:
> 
> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
> return super(JsonRequest, self)._handle_exception(exception)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
> raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
> File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
> raise value
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
> result = self._call_function(**self.params)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
> return checked_call(self.db, *args, **kwargs)
> File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
> return f(dbname, *args, **kwargs)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
> result = self.endpoint(*a, **kw)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in **call**
> return self.method(*args, **kw)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
> response = f(*args, **kw)
> File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
> action = self._call_kw(model, method, args, {})
> File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
> return call_kw(request.env[model], method, args, kwargs)
> File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
> return _call_kw_multi(method, model, args, kwargs)
> File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
> result = method(recs, *args, **kwargs)
> File "/mnt/extra-addons/dgii_reports/models/dgii_report.py", line 830, in generate_report
> self._generate_report()
> File "/mnt/extra-addons/dgii_reports/models/dgii_report.py", line 818, in _generate_report
> self._compute_607_data()
> File "/mnt/extra-addons/dgii_reports/models/dgii_report.py", line 618, in _compute_607_data
> payments = self._get_sale_payments_forms(inv)
> File "/mnt/extra-addons/dgii_reports/models/dgii_report.py", line 446, in _get_sale_payments_forms
> for payment in Invoice._get_invoice_payment_widget(invoice_id):
> TypeError: _get_invoice_payment_widget() takes 1 positional argument but 2 were given

A mi también al intentar generar el mes de noviembre exclusivamente:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/dgii_reports/models/dgii_report.py", line 830, in generate_report
    self._generate_report()
  File "/opt/odoo/addons/dgii_reports/models/dgii_report.py", line 818, in _generate_report
    self._compute_607_data()
  File "/opt/odoo/addons/dgii_reports/models/dgii_report.py", line 618, in _compute_607_data
    payments = self._get_sale_payments_forms(inv)
  File "/opt/odoo/addons/dgii_reports/models/dgii_report.py", line 446, in _get_sale_payments_forms
    for payment in Invoice._get_invoice_payment_widget(invoice_id):
TypeError: _get_invoice_payment_widget() takes 1 positional argument but 2 were given
