### ISSUE TITLE
Error al intentar comprobar un comprobante fiscal en compras

### ISSUE THREAD

**Issue by OverloadSolutions** [odoo-dominicana/l10n-dominicana#577]
Error al colocar el numero de comprobante fiscal en compra:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/models.py", line 5469, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo12/odoo/odoo/models.py", line 5322, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo12/odoo/addons/ncf_manager/models/account_invoice.py", line 279, in onchange_ncf
    self.validate_fiscal_purchase()
  File "/opt/odoo12/odoo/addons/ncf_manager/models/account_invoice.py", line 192, in validate_fiscal_purchase
    not ncf_validation.check_dgii(self.partner_id.vat, NCF)):
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/stdnum/do/ncf.py", line 176, in check_dgii
    validation = document.find('.//input[@name="__EVENTVALIDATION"]').get('value')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by jeffryjdelarosa** [comment]
@OverloadSolutions debes a hacer el git pull de la comunidad y luego
`pip3 install --no-cache-dir --upgrade 'git+https://github.com/arthurdejong/python-stdnum.git@f7b968c986ad6163f92e1c72da20050f961f8954'`
