### ISSUE TITLE
Odoo 12 no puede leer la propiedad colspan

### ISSUE THREAD

**Issue by Yohanselfausto** [odoo-dominicana/l10n-dominicana#608]
**Impacted versions**
Odoo 12

**Steps to reproduce**
Instalar Odoo 12, añadir el plug-in de inventario, de contabilidad, punto de venta o NCF manager, luego dirigirse a ajustes / Técnico / Secuencias e identificadores y tratar de acceder a cualquier menú para modificar una secuencia.
**Current behavior**
Uncaught TypeError: Cannot read property 'colspan' of undefined
http://localhost:8069/web/static/src/js/views/form/form_renderer.js:527
Traceback:
TypeError: Cannot read property 'colspan' of undefined
    at http://localhost:8069/web/static/src/js/views/form/form_renderer.js:527:48
    at Function..each..forEach (http://localhost:8069/web/static/lib/underscore/underscore.js:145:9)
    at Class._renderInnerGroup (http://localhost:8069/web/static/src/js/views/form/form_renderer.js:519:11)
    at Class._renderTagGroup (http://localhost:8069/web/static/src/js/views/form/form_renderer.js:747:25)
    at Class._renderNode [as _super] (http://localhost:8069/web/static/src/js/views/form/form_renderer.js:614:29)
    at Class._renderNode (http://localhost:8069/mail/static/src/js/form_renderer.js:66:32)
    at Class._renderNode (http://localhost:8069/web/static/src/js/core/class.js:123:38)
    at http://localhost:8069/web/static/src/js/views/form/form_renderer.js:643:31
    at Function..map..collect (http://localhost:8069/web/static/lib/underscore/underscore.js:164:24)
    at Class._renderOuterGroup (http://localhost:8069/web/static/src/js/views/form/form_renderer.js:639:26)

**Expected behavior**
Debería tener acceso a modificar cualquiera de las secuencias, pero no puedo acceder a ninguna.

**Comment by jlopezg** [comment]
@Yohanselfausto podrías por favor utilizar el siguiente esquema para definir el issue:

#### Impacted versions

#### Steps to reproduce

#### Current behavior

#### Expected behavior

#### Video/Screenshot link (optional)

**Comment by Yohanselfausto** [comment]
> @Yohanselfausto podrías por favor utilizar el siguiente esquema para definir el issue:
> 
> #### Impacted versions
> #### Steps to reproduce
> #### Current behavior
> #### Expected behavior
> #### Video/Screenshot link (optional)

Listo estimado espero pueda asistirme.

**Comment by jlopezg** [comment]
@Yohanselfausto 

* En **Impacted versions** necesito el branch de este repositorio, no la versión de Odoo.

* En **Steps to reproduce** necesito:
   - Sistema operativo
   - Que actualices tu repositorio de Odoo al último commit
   - Que instales lo mínimo. Trata de identificar cuál de los módulos es que causa el error.

* En **Video/Screenshot link** compartas un video desde la creación de la base de datos, la instalación del módulo que presenta el error hasta el momento en que se muestra el error. Puedes usar el pluggin Screencastify de Google Chrome para esto.

**Comment by Yohanselfausto** [comment]
La solución fue actualizar el repositorio de Odoo al último commit
