### ISSUE TITLE
On credito not creation

### ISSUE THREAD

**Issue by juhenriquez** [odoo-dominicana/l10n-dominicana#652]
Type: General
When  trying to generate credit note on provider invoice

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/opt/odoo/odoo/models.py", line 1528, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: El campo `account_id` no existe

Contexto del error:
Vista `account.move.reversal.form`
[view_id: 551, xml_id: account.view_account_move_reversal, model: account.move.reversal, parent_id: n/a]

![2020-07-29 14_12_26-Window](https://user-images.githubusercontent.com/8250019/88837075-b5e95c00-d1a5-11ea-8ce7-c8925a1a3502.png)
![2020-07-29 14_12_35-Window](https://user-images.githubusercontent.com/8250019/88837078-b681f280-d1a5-11ea-969c-8cbfe85de974.png)

**Comment by jlopezg** [comment]
El issue fue corregido o no se pudo reproducir.
