### ISSUE TITLE
[14.0][l10n_do_accounting] Error al instalar Fiscal Accounting

### ISSUE THREAD

**Issue by anyeloroy** [odoo-dominicana/l10n-dominicana#686]
Type: Error al instalar Fiscal Accounting

**Describe the bug**
Odoo Version: Odoo 14.0-20201001 (Community Edition)
Intentando instalar el modulo Fiscal Accounting presenta el error a continuación.

**Steps to Reproduce**
1. Go to 'Apps'
2. Click on 'Buscar l10n_do'
3. Scroll down to 'seleccionar l10n_do_accounting y click en instalar'

**Expected behavior**
Que instale la el modulo de fiscal account RD para la version 14.0 CE

**Additional context and screenshots**
[Add any other information such as screenshots, videos, messages]
![Error al instalar](https://user-images.githubusercontent.com/42875307/97116312-9e513f00-16d2-11eb-8357-86394661994b.jpg)

**Sample Code / Stack Trace**
```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 197, in load_module_graph
    registry.setup_models(cr)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/registry.py", line 265, in setup_models
    model._setup_fields()
  File "/usr/local/lib/python3.7/site-packages/odoo/models.py", line 2817, in _setup_fields
    field.setup_full(self)
  File "/usr/local/lib/python3.7/site-packages/odoo/fields.py", line 400, in setup_full
    self._setup_regular_full(model)
  File "/usr/local/lib/python3.7/site-packages/odoo/fields.py", line 3035, in _setup_regular_full
    invf = comodel._fields[self.inverse_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'l10n_latam_journal_id'
```

**Configuration information**
Operating System: Imagen Docker corriendo en windows y tambien se hizo la prueba en google cloud platforma (kubernetes).
Python version: Python 3.7.9 (default, Sep 10 2020, 17:21:15) [GCC 8.3.0] on linux
Node Version: v10.21.0
Postgres: psql (13.0 (Debian 13.0-1.pgdg100+1))

**Comment by U31664** [comment]
Hola @jlopezg,

Crees que me puedas orientar a validar este error?

Saludos,

**Comment by anyeloroy** [comment]
Hola @jlopezg ,

Crees que me puedas orientar a validar este error?

Saludos,

**Comment by jlopezg** [comment]
Hola @anyeloroy 

Aún no se ha adaptado la localización a la versión 14.

**Comment by anyeloroy** [comment]
Hola @jlopezg ,

Gracias por la informacion, disculpa, existe alguna guia de como adaptarlo, para ver si puedo iniciar a documentarme.

PD: Soy nuevo en odoo.

Saludos,

**Comment by jlopezg** [comment]
Hola @anyeloroy

Odoo es un mundo muy amplio. Te recomiendo hacer cursos de Python y POO para empezar.

La documentación para desarrolladores es esta: https://www.odoo.com/documentation/14.0/

Sobre la adaptación de los módulos entre versiones, no hay una documentación más precisa que el propio código, sus commits y Pull Requests.

**Comment by anyeloroy** [comment]
Hola @jlopezg ,

Gracias por la recomendaciones, estaremos validando las documentacion.

Saludos,
