### ISSUE TITLE
Error luego de instalacion del modulo l10n_do_pos

### ISSUE THREAD

**Issue by ypolanco1982** [odoo-dominicana/l10n-dominicana#715]
Impacted versions:

 - 13.0

Steps to reproduce:

 1. Configurar el diario Point of Sale, activando el campo Es fiscal.
 2. Configurando el modulo de punto de ventas, activado la opcion de contabilidad
 3. Asignar el diario Point of Sale por defecto y el cliente por defecto
 4. Ingresar al punto de venta previamente configurado y realizar varias facturas
                4.1 Pude registrar varias facturas sin problema alguno y fue asignado el comprobante correctamente.
 5. Salgo de facturacion (presionando el boton CLOSE y salgo de la pantalla) hasta aqui todo va bien.

 A partir de aqui:
 6.  al intentar cerrar la session presionando el boton de Validar y Registrar Asientos, me presenta el siguiente mensaje:
                6.1 The journal require a document type but not document type has been selected on invoices [26].
 7. al reanudar la session me presenta la pantalla con la idicacion de que no tengo conexion 
 8. al intentar hacer una nueva factura me presenta unos mensajes de errores.
 9. al salir y limpiar cache me permite facturar nuevamente sin problema pero me vuela un numero de comprobante
10. al salir e ingresar nuevamente me presenta los mismos errores antes mensionados.

![error cierre caja](https://user-images.githubusercontent.com/59124818/101392612-5bbb7e80-389c-11eb-8e03-d7f83b8c76ad.PNG)
![error cierre caja2](https://user-images.githubusercontent.com/59124818/101392613-5c541500-389c-11eb-9d7f-e2ea0b863b44.PNG)

**Comment by ypolanco1982** [comment]
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1004, in __get__
    value = env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.move(5,).l10n_latam_sequence_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\point_of_sale\models\pos_order.py", line 443, in create_from_ui
    order_ids.append(self._process_order(order, draft, existing_order))
  File "c:\program files (x86)\odoo 13.0\server\odoo\addons_extra\l10n_do_pos\models\pos_order.py", line 203, in _process_order
    return super(PosOrder, self)._process_order(order, draft, existing_order)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\point_of_sale\models\pos_order.py", line 139, in _process_order
    pos_order.action_pos_order_invoice()
  File "c:\program files (x86)\odoo 13.0\server\odoo\addons_extra\l10n_do_pos\models\pos_order.py", line 283, in action_pos_order_invoice
    res = super(PosOrder, self).action_pos_order_invoice()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\point_of_sale\models\pos_order.py", line 401, in action_pos_order_invoice
    new_move.sudo().with_context(force_company=order.company_id.id).post()
  File "c:\program files (x86)\odoo 13.0\server\odoo\addons_extra\l10n_do_accounting\models\account_move.py", line 544, in post
    res = super(AccountMove, self).post()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\purchase_stock\models\account_invoice.py", line 182, in post
    return super(AccountMove, self).post()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\stock_account\models\account_move.py", line 52, in post
    res = super(AccountMove, self).post()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\l10n_latam_invoice_document\models\account_move.py", line 129, in post
    if not rec.l10n_latam_sequence_id:
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 2333, in __get__
    return super().__get__(records, owner)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1028, in __get__
    self.compute_value(recs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1113, in compute_value
    records._compute_field_value(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3981, in _compute_field_value
    getattr(self, field.compute)()
TypeError: 'ir.sequence' object is not callable

**Comment by raulovallet** [comment]
@ypolanco1982 podrías confirmar cuál de los dos diarios colocaste como fiscal?

<img width="1224" alt="Screen Shot 2020-12-08 at 9 54 13 AM" src="https://user-images.githubusercontent.com/23384474/101492813-96282880-393b-11eb-8927-0171c1d36d68.png">

**Comment by jlopezg** [comment]
Cerrado porque el módulo no está terminado.

**Comment by ypolanco1982** [comment]
Point Of Sale (DOP)
